language: go
go:
  - 1.x
services: mongodb
notifications:
  email: falses
install:
  - go get -u -v github.com/go-task/task/cmd/task
  - cd $GOPATH
  - mkdir -p {src,bin,pkg}
  - mkdir -p src/github.com/globalsign/
  - cd src/github.com/globalsign/
  - git clone https://github.com/ddspog/mgo.git
  - cd mgo/
  - cd $GOPATH/src/github.com/ddspog/mongo/
  - go get -t ./...
beforeScript:
  - sleep 15
script:
  - task test-unit