language: go
go:
  - 1.x
services: mongodb
notifications:
  email: falses
install:
  - go get -u golang.org/x/vgo
  - go get -u -v github.com/go-task/task/cmd/task
  - vgo build
beforeScript:
  - sleep 15
script:
  - task test