// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ddspog/mongo (interfaces: Querier)

package mongo

import (
	gomock "github.com/golang/mock/gomock"
	mgo_v2 "gopkg.in/mgo.v2"
	reflect "reflect"
	time "time"
)

// mockQuerier is a mock of Querier interface
type mockQuerier struct {
	ctrl     *gomock.Controller
	recorder *mockQuerierMockRecorder
}

// mockQuerierMockRecorder is the mock recorder for mockQuerier
type mockQuerierMockRecorder struct {
	mock *mockQuerier
}

// newMockQuerier creates a new mock instance
func newMockQuerier(ctrl *gomock.Controller) *mockQuerier {
	mock := &mockQuerier{ctrl: ctrl}
	mock.recorder = &mockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *mockQuerier) EXPECT() *mockQuerierMockRecorder {
	return m.recorder
}

// All mocks base method
func (m *mockQuerier) All(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "All", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// All indicates an expected call of All
func (mr *mockQuerierMockRecorder) All(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*mockQuerier)(nil).All), arg0)
}

// Apply mocks base method
func (m *mockQuerier) Apply(arg0 mgo_v2.Change, arg1 interface{}) (*mgo_v2.ChangeInfo, error) {
	ret := m.ctrl.Call(m, "Apply", arg0, arg1)
	ret0, _ := ret[0].(*mgo_v2.ChangeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apply indicates an expected call of Apply
func (mr *mockQuerierMockRecorder) Apply(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*mockQuerier)(nil).Apply), arg0, arg1)
}

// Batch mocks base method
func (m *mockQuerier) Batch(arg0 int) Querier {
	ret := m.ctrl.Call(m, "Batch", arg0)
	ret0, _ := ret[0].(Querier)
	return ret0
}

// Batch indicates an expected call of Batch
func (mr *mockQuerierMockRecorder) Batch(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Batch", reflect.TypeOf((*mockQuerier)(nil).Batch), arg0)
}

// Comment mocks base method
func (m *mockQuerier) Comment(arg0 string) Querier {
	ret := m.ctrl.Call(m, "Comment", arg0)
	ret0, _ := ret[0].(Querier)
	return ret0
}

// Comment indicates an expected call of Comment
func (mr *mockQuerierMockRecorder) Comment(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Comment", reflect.TypeOf((*mockQuerier)(nil).Comment), arg0)
}

// Count mocks base method
func (m *mockQuerier) Count() (int, error) {
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count
func (mr *mockQuerierMockRecorder) Count() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*mockQuerier)(nil).Count))
}

// Distinct mocks base method
func (m *mockQuerier) Distinct(arg0 string, arg1 interface{}) error {
	ret := m.ctrl.Call(m, "Distinct", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Distinct indicates an expected call of Distinct
func (mr *mockQuerierMockRecorder) Distinct(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Distinct", reflect.TypeOf((*mockQuerier)(nil).Distinct), arg0, arg1)
}

// Explain mocks base method
func (m *mockQuerier) Explain(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "Explain", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Explain indicates an expected call of Explain
func (mr *mockQuerierMockRecorder) Explain(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Explain", reflect.TypeOf((*mockQuerier)(nil).Explain), arg0)
}

// For mocks base method
func (m *mockQuerier) For(arg0 interface{}, arg1 func() error) error {
	ret := m.ctrl.Call(m, "For", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// For indicates an expected call of For
func (mr *mockQuerierMockRecorder) For(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "For", reflect.TypeOf((*mockQuerier)(nil).For), arg0, arg1)
}

// Hint mocks base method
func (m *mockQuerier) Hint(arg0 ...string) Querier {
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Hint", varargs...)
	ret0, _ := ret[0].(Querier)
	return ret0
}

// Hint indicates an expected call of Hint
func (mr *mockQuerierMockRecorder) Hint(arg0 ...interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hint", reflect.TypeOf((*mockQuerier)(nil).Hint), arg0...)
}

// Iter mocks base method
func (m *mockQuerier) Iter() *mgo_v2.Iter {
	ret := m.ctrl.Call(m, "Iter")
	ret0, _ := ret[0].(*mgo_v2.Iter)
	return ret0
}

// Iter indicates an expected call of Iter
func (mr *mockQuerierMockRecorder) Iter() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Iter", reflect.TypeOf((*mockQuerier)(nil).Iter))
}

// Limit mocks base method
func (m *mockQuerier) Limit(arg0 int) Querier {
	ret := m.ctrl.Call(m, "Limit", arg0)
	ret0, _ := ret[0].(Querier)
	return ret0
}

// Limit indicates an expected call of Limit
func (mr *mockQuerierMockRecorder) Limit(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Limit", reflect.TypeOf((*mockQuerier)(nil).Limit), arg0)
}

// LogReplay mocks base method
func (m *mockQuerier) LogReplay() Querier {
	ret := m.ctrl.Call(m, "LogReplay")
	ret0, _ := ret[0].(Querier)
	return ret0
}

// LogReplay indicates an expected call of LogReplay
func (mr *mockQuerierMockRecorder) LogReplay() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogReplay", reflect.TypeOf((*mockQuerier)(nil).LogReplay))
}

// MapReduce mocks base method
func (m *mockQuerier) MapReduce(arg0 *mgo_v2.MapReduce, arg1 interface{}) (*mgo_v2.MapReduceInfo, error) {
	ret := m.ctrl.Call(m, "MapReduce", arg0, arg1)
	ret0, _ := ret[0].(*mgo_v2.MapReduceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MapReduce indicates an expected call of MapReduce
func (mr *mockQuerierMockRecorder) MapReduce(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapReduce", reflect.TypeOf((*mockQuerier)(nil).MapReduce), arg0, arg1)
}

// One mocks base method
func (m *mockQuerier) One(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "One", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// One indicates an expected call of One
func (mr *mockQuerierMockRecorder) One(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "One", reflect.TypeOf((*mockQuerier)(nil).One), arg0)
}

// Prefetch mocks base method
func (m *mockQuerier) Prefetch(arg0 float64) Querier {
	ret := m.ctrl.Call(m, "Prefetch", arg0)
	ret0, _ := ret[0].(Querier)
	return ret0
}

// Prefetch indicates an expected call of Prefetch
func (mr *mockQuerierMockRecorder) Prefetch(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prefetch", reflect.TypeOf((*mockQuerier)(nil).Prefetch), arg0)
}

// Select mocks base method
func (m *mockQuerier) Select(arg0 interface{}) Querier {
	ret := m.ctrl.Call(m, "Select", arg0)
	ret0, _ := ret[0].(Querier)
	return ret0
}

// Select indicates an expected call of Select
func (mr *mockQuerierMockRecorder) Select(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*mockQuerier)(nil).Select), arg0)
}

// SetMaxScan mocks base method
func (m *mockQuerier) SetMaxScan(arg0 int) Querier {
	ret := m.ctrl.Call(m, "SetMaxScan", arg0)
	ret0, _ := ret[0].(Querier)
	return ret0
}

// SetMaxScan indicates an expected call of SetMaxScan
func (mr *mockQuerierMockRecorder) SetMaxScan(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaxScan", reflect.TypeOf((*mockQuerier)(nil).SetMaxScan), arg0)
}

// SetMaxTime mocks base method
func (m *mockQuerier) SetMaxTime(arg0 time.Duration) Querier {
	ret := m.ctrl.Call(m, "SetMaxTime", arg0)
	ret0, _ := ret[0].(Querier)
	return ret0
}

// SetMaxTime indicates an expected call of SetMaxTime
func (mr *mockQuerierMockRecorder) SetMaxTime(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaxTime", reflect.TypeOf((*mockQuerier)(nil).SetMaxTime), arg0)
}

// Skip mocks base method
func (m *mockQuerier) Skip(arg0 int) Querier {
	ret := m.ctrl.Call(m, "Skip", arg0)
	ret0, _ := ret[0].(Querier)
	return ret0
}

// Skip indicates an expected call of Skip
func (mr *mockQuerierMockRecorder) Skip(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Skip", reflect.TypeOf((*mockQuerier)(nil).Skip), arg0)
}

// Snapshot mocks base method
func (m *mockQuerier) Snapshot() Querier {
	ret := m.ctrl.Call(m, "Snapshot")
	ret0, _ := ret[0].(Querier)
	return ret0
}

// Snapshot indicates an expected call of Snapshot
func (mr *mockQuerierMockRecorder) Snapshot() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*mockQuerier)(nil).Snapshot))
}

// Sort mocks base method
func (m *mockQuerier) Sort(arg0 ...string) Querier {
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Sort", varargs...)
	ret0, _ := ret[0].(Querier)
	return ret0
}

// Sort indicates an expected call of Sort
func (mr *mockQuerierMockRecorder) Sort(arg0 ...interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sort", reflect.TypeOf((*mockQuerier)(nil).Sort), arg0...)
}

// Tail mocks base method
func (m *mockQuerier) Tail(arg0 time.Duration) *mgo_v2.Iter {
	ret := m.ctrl.Call(m, "Tail", arg0)
	ret0, _ := ret[0].(*mgo_v2.Iter)
	return ret0
}

// Tail indicates an expected call of Tail
func (mr *mockQuerierMockRecorder) Tail(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tail", reflect.TypeOf((*mockQuerier)(nil).Tail), arg0)
}
