// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ddspog/mongo (interfaces: Collectioner)

package mongo

import (
	gomock "github.com/golang/mock/gomock"
	mgo_v2 "gopkg.in/mgo.v2"
	bson "gopkg.in/mgo.v2/bson"
	reflect "reflect"
)

// mockCollectioner is a mock of Collectioner interface
type mockCollectioner struct {
	ctrl     *gomock.Controller
	recorder *mockCollectionerMockRecorder
}

// mockCollectionerMockRecorder is the mock recorder for mockCollectioner
type mockCollectionerMockRecorder struct {
	mock *mockCollectioner
}

// newMockCollectioner creates a new mock instance
func newMockCollectioner(ctrl *gomock.Controller) *mockCollectioner {
	mock := &mockCollectioner{ctrl: ctrl}
	mock.recorder = &mockCollectionerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *mockCollectioner) EXPECT() *mockCollectionerMockRecorder {
	return m.recorder
}

// Bulk mocks base method
func (m *mockCollectioner) Bulk() *mgo_v2.Bulk {
	ret := m.ctrl.Call(m, "Bulk")
	ret0, _ := ret[0].(*mgo_v2.Bulk)
	return ret0
}

// Bulk indicates an expected call of Bulk
func (mr *mockCollectionerMockRecorder) Bulk() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bulk", reflect.TypeOf((*mockCollectioner)(nil).Bulk))
}

// Count mocks base method
func (m *mockCollectioner) Count() (int, error) {
	ret := m.ctrl.Call(m, "Count")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count
func (mr *mockCollectionerMockRecorder) Count() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*mockCollectioner)(nil).Count))
}

// Create mocks base method
func (m *mockCollectioner) Create(arg0 *mgo_v2.CollectionInfo) error {
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *mockCollectionerMockRecorder) Create(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*mockCollectioner)(nil).Create), arg0)
}

// DropCollection mocks base method
func (m *mockCollectioner) DropCollection() error {
	ret := m.ctrl.Call(m, "DropCollection")
	ret0, _ := ret[0].(error)
	return ret0
}

// DropCollection indicates an expected call of DropCollection
func (mr *mockCollectionerMockRecorder) DropCollection() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropCollection", reflect.TypeOf((*mockCollectioner)(nil).DropCollection))
}

// DropIndex mocks base method
func (m *mockCollectioner) DropIndex(arg0 ...string) error {
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DropIndex", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DropIndex indicates an expected call of DropIndex
func (mr *mockCollectionerMockRecorder) DropIndex(arg0 ...interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropIndex", reflect.TypeOf((*mockCollectioner)(nil).DropIndex), arg0...)
}

// DropIndexName mocks base method
func (m *mockCollectioner) DropIndexName(arg0 string) error {
	ret := m.ctrl.Call(m, "DropIndexName", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DropIndexName indicates an expected call of DropIndexName
func (mr *mockCollectionerMockRecorder) DropIndexName(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropIndexName", reflect.TypeOf((*mockCollectioner)(nil).DropIndexName), arg0)
}

// EnsureIndex mocks base method
func (m *mockCollectioner) EnsureIndex(arg0 mgo_v2.Index) error {
	ret := m.ctrl.Call(m, "EnsureIndex", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureIndex indicates an expected call of EnsureIndex
func (mr *mockCollectionerMockRecorder) EnsureIndex(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureIndex", reflect.TypeOf((*mockCollectioner)(nil).EnsureIndex), arg0)
}

// EnsureIndexKey mocks base method
func (m *mockCollectioner) EnsureIndexKey(arg0 ...string) error {
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EnsureIndexKey", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureIndexKey indicates an expected call of EnsureIndexKey
func (mr *mockCollectionerMockRecorder) EnsureIndexKey(arg0 ...interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureIndexKey", reflect.TypeOf((*mockCollectioner)(nil).EnsureIndexKey), arg0...)
}

// Find mocks base method
func (m *mockCollectioner) Find(arg0 interface{}) Querier {
	ret := m.ctrl.Call(m, "Find", arg0)
	ret0, _ := ret[0].(Querier)
	return ret0
}

// Find indicates an expected call of Find
func (mr *mockCollectionerMockRecorder) Find(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*mockCollectioner)(nil).Find), arg0)
}

// FindId mocks base method
func (m *mockCollectioner) FindId(arg0 interface{}) Querier {
	ret := m.ctrl.Call(m, "FindId", arg0)
	ret0, _ := ret[0].(Querier)
	return ret0
}

// FindId indicates an expected call of FindId
func (mr *mockCollectionerMockRecorder) FindId(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindId", reflect.TypeOf((*mockCollectioner)(nil).FindId), arg0)
}

// Indexes mocks base method
func (m *mockCollectioner) Indexes() ([]mgo_v2.Index, error) {
	ret := m.ctrl.Call(m, "Indexes")
	ret0, _ := ret[0].([]mgo_v2.Index)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Indexes indicates an expected call of Indexes
func (mr *mockCollectionerMockRecorder) Indexes() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Indexes", reflect.TypeOf((*mockCollectioner)(nil).Indexes))
}

// Insert mocks base method
func (m *mockCollectioner) Insert(arg0 ...interface{}) error {
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Insert", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert
func (mr *mockCollectionerMockRecorder) Insert(arg0 ...interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*mockCollectioner)(nil).Insert), arg0...)
}

// NewIter mocks base method
func (m *mockCollectioner) NewIter(arg0 *mgo_v2.Session, arg1 []bson.Raw, arg2 int64, arg3 error) *mgo_v2.Iter {
	ret := m.ctrl.Call(m, "NewIter", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*mgo_v2.Iter)
	return ret0
}

// NewIter indicates an expected call of NewIter
func (mr *mockCollectionerMockRecorder) NewIter(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIter", reflect.TypeOf((*mockCollectioner)(nil).NewIter), arg0, arg1, arg2, arg3)
}

// Pipe mocks base method
func (m *mockCollectioner) Pipe(arg0 interface{}) *mgo_v2.Pipe {
	ret := m.ctrl.Call(m, "Pipe", arg0)
	ret0, _ := ret[0].(*mgo_v2.Pipe)
	return ret0
}

// Pipe indicates an expected call of Pipe
func (mr *mockCollectionerMockRecorder) Pipe(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pipe", reflect.TypeOf((*mockCollectioner)(nil).Pipe), arg0)
}

// Remove mocks base method
func (m *mockCollectioner) Remove(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "Remove", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove
func (mr *mockCollectionerMockRecorder) Remove(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*mockCollectioner)(nil).Remove), arg0)
}

// RemoveAll mocks base method
func (m *mockCollectioner) RemoveAll(arg0 interface{}) (*ChangeInfo, error) {
	ret := m.ctrl.Call(m, "RemoveAll", arg0)
	ret0, _ := ret[0].(*ChangeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveAll indicates an expected call of RemoveAll
func (mr *mockCollectionerMockRecorder) RemoveAll(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAll", reflect.TypeOf((*mockCollectioner)(nil).RemoveAll), arg0)
}

// RemoveId mocks base method
func (m *mockCollectioner) RemoveId(arg0 interface{}) error {
	ret := m.ctrl.Call(m, "RemoveId", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveId indicates an expected call of RemoveId
func (mr *mockCollectionerMockRecorder) RemoveId(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveId", reflect.TypeOf((*mockCollectioner)(nil).RemoveId), arg0)
}

// Repair mocks base method
func (m *mockCollectioner) Repair() *mgo_v2.Iter {
	ret := m.ctrl.Call(m, "Repair")
	ret0, _ := ret[0].(*mgo_v2.Iter)
	return ret0
}

// Repair indicates an expected call of Repair
func (mr *mockCollectionerMockRecorder) Repair() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Repair", reflect.TypeOf((*mockCollectioner)(nil).Repair))
}

// Update mocks base method
func (m *mockCollectioner) Update(arg0, arg1 interface{}) error {
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *mockCollectionerMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*mockCollectioner)(nil).Update), arg0, arg1)
}

// UpdateAll mocks base method
func (m *mockCollectioner) UpdateAll(arg0, arg1 interface{}) (*ChangeInfo, error) {
	ret := m.ctrl.Call(m, "UpdateAll", arg0, arg1)
	ret0, _ := ret[0].(*ChangeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAll indicates an expected call of UpdateAll
func (mr *mockCollectionerMockRecorder) UpdateAll(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAll", reflect.TypeOf((*mockCollectioner)(nil).UpdateAll), arg0, arg1)
}

// UpdateId mocks base method
func (m *mockCollectioner) UpdateId(arg0, arg1 interface{}) error {
	ret := m.ctrl.Call(m, "UpdateId", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateId indicates an expected call of UpdateId
func (mr *mockCollectionerMockRecorder) UpdateId(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateId", reflect.TypeOf((*mockCollectioner)(nil).UpdateId), arg0, arg1)
}

// Upsert mocks base method
func (m *mockCollectioner) Upsert(arg0, arg1 interface{}) (*ChangeInfo, error) {
	ret := m.ctrl.Call(m, "Upsert", arg0, arg1)
	ret0, _ := ret[0].(*ChangeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert
func (mr *mockCollectionerMockRecorder) Upsert(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*mockCollectioner)(nil).Upsert), arg0, arg1)
}

// UpsertId mocks base method
func (m *mockCollectioner) UpsertId(arg0, arg1 interface{}) (*ChangeInfo, error) {
	ret := m.ctrl.Call(m, "UpsertId", arg0, arg1)
	ret0, _ := ret[0].(*ChangeInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertId indicates an expected call of UpsertId
func (mr *mockCollectionerMockRecorder) UpsertId(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertId", reflect.TypeOf((*mockCollectioner)(nil).UpsertId), arg0, arg1)
}

// With mocks base method
func (m *mockCollectioner) With(arg0 *mgo_v2.Session) Collectioner {
	ret := m.ctrl.Call(m, "With", arg0)
	ret0, _ := ret[0].(Collectioner)
	return ret0
}

// With indicates an expected call of With
func (mr *mockCollectionerMockRecorder) With(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "With", reflect.TypeOf((*mockCollectioner)(nil).With), arg0)
}
