test-handler:
  desc: Run handler tests.
  cmds:
    - echo "Calling tests handler execution ..."
    - go test {{.REPO_PATH}}/handler -v --cover
  silent: true

test-model:
  desc: Run model tests.
  cmds:
    - echo "Calling tests model execution ..."
    - go test {{.REPO_PATH}}/model -v --cover
  silent: true

test-example:
  desc: Run a test with an mongo instance running.
  cmds:
    - echo "Calling tests example execution ..."
    - go test {{.REPO_PATH}}/example -v --cover
  silent: true

test-mongo:
  desc: Run mongo tests.
  cmds:
    - echo "Calling tests mongo execution ..."
    - go test {{.REPO_PATH}} -v --cover
  silent: true

test:
  deps: [test-handler, test-model, test-mongo, test-example]
  desc: Run all tests.

gen-mock-collection:
  cmds:
    - echo "Generating Mock for mgo.Collection ..."
    - mockgen -destination=genmocks/mock_collection.go -package=genmocks {{.MGO_INTERFACES_PACKAGE}} Collectioner

gen-mock-database:
  cmds:
    - echo "Generating Mock for mgo.Database ..."
    - mockgen -destination=genmocks/mock_database.go -package=genmocks {{.MGO_INTERFACES_PACKAGE}} Databaser

gen-mock-query:
  cmds:
    - echo "Generating Mock for mgo.Query ..."
    - mockgen -destination=genmocks/mock_query.go -package=genmocks {{.MGO_INTERFACES_PACKAGE}} Querier

gen-mock-session:
  cmds:
    - echo "Generating Mock for mgo.Session ..."
    - mockgen -destination=genmocks/mock_session.go -package=genmocks {{.MGO_INTERFACES_PACKAGE}} Sessioner

gen-mock-control:
  cmds:
    - echo "Generating Mock for Controller ..."
    - mockgen -destination=genmocks/mock_control.go -package=genmocks {{.MGO_INTERFACES_PACKAGE}} Controller

format:
  cmds:
    - echo "Formatting all files on the project ..."
    - gofmt -e -s -w .

vendor-mgo:
  cmds:
    - echo "Vendoring latest version of mgo package ..."
    - govendor fetch github.com/globalsign/mgo
  desc: Vendor mgo package.

vendor-sync:
  cmds:
    - echo "Syncing vendor information ..."
    - govendor sync 
  desc: Sync all vendor pacakges.

vendor:
  deps: [vendor-mgo, vendor-sync]
  desc: Vendor all needed packages.

push:
  cmds:
    - git push
    - git push --tags
  desc: Push code to git remote.