test-connecter:
  desc: Run connecter tests.
  cmds:
    - echo "Calling tests connecter execution ..."
    - go test {{.REPO_PATH}}/internal/connecter -v --cover
  silent: true

test-mongo:
  desc: Run mongo tests.
  cmds:
    - echo "Calling tests mongo execution ..."
    - go test {{.REPO_PATH}} -v --cover
  silent: true

test-acceptance:
  desc: Run acceptance tests with a real mongo instance running.
  cmds:
    - echo "Calling acceptance tests execution ..."
    - go test {{.REPO_PATH}} -v --cover -tags=acceptance
  silent: true

cover:
  desc: Check cover of all unit tests.
  cmds:
    - echo "Checking coverage for all unit tests ..."
    - goverage ./...
    - go tool cover -html=coverage.out

test:
  deps: [test-connecter, test-mongo, test-acceptance]
  desc: Run all tests.

format:
  cmds:
    - echo "Formatting all files on the project ..."
    - gofmt -e -s -w .