test-handler:
  desc: Run handler tests.
  cmds:
    - echo "Calling tests handler execution ..."
    - go test {{.REPO_PATH}}/handler -v
  silent: true

test-model:
  desc: Run model tests.
  cmds:
    - echo "Calling tests model execution ..."
    - go test {{.REPO_PATH}}/model -v
  silent: true

test:
  deps: [test-handler, test-model]
  desc: Run all tests.


gen-mock-collection:
  cmds:
    - echo "Generating Mock for mgo.Collection ..."
    - mockgen -destination=mock_collection.go -package=mocks {{.MGO_INTERFACES_PACKAGE}} Collectioner

gen-mock-database:
  cmds:
    - echo "Generating Mock for mgo.Database ..."
    - mockgen -destination=mock_database.go -package=mocks {{.MGO_INTERFACES_PACKAGE}} Databaser

gen-mock-query:
  cmds:
    - echo "Generating Mock for mgo.Query ..."
    - mockgen -destination=mock_query.go -package=mocks {{.MGO_INTERFACES_PACKAGE}} Querier

format:
  cmds:
    - echo "Formatting all files on the project ..."
    - gofmt -e -s -w .

vendor-mgo:
  cmds:
    - echo "Vendoring latest version of mgo package ..."
    - govendor fetch gopkg.in/mgo.v2
  desc: Vendor mgo package.

vendor-sync:
  cmds:
    - echo "Syncing vendor information ..."
    - govendor sync 

vendor:
  deps: [vendor-mgo, vendor-sync]
  desc: Vendo all needed packages.